export const SEARCH_ZAKUP='SEARCH_ZAKUP';
export const UPDATE_START_PRICE='UPDATE_START_PRICE';
export const UPDATE_END_PRICE='UPDATE_END_PRICE';
export const UPDATE_CHECKBOX_VALUE='UPDATE_CHECKBOX_VALUE';
export const UPDATE_LOADING='UPDATE_LOADING';
export const UPDATE_DATA='UPDATE_DATA';